# Generated by Django 4.0.2 on 2022-03-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_server', '0002_alter_bots_options_rename_title_bots_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='bots',
            name='subscription',
            field=models.BooleanField(default=True, verbose_name='Подписка'),
        ),
    ]
