# Generated by Django 4.0.2 on 2022-03-16 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micro_server', '0003_bots_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bots',
            name='subscription',
        ),
    ]
