# Generated by Django 4.0.2 on 2022-03-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_server', '0004_remove_bots_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('publication', models.DateTimeField(auto_now_add=True, verbose_name='Дата Пуликации')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-publication', 'title'],
            },
        ),
    ]
