# Generated by Django 4.0.2 on 2022-03-16 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('micro_server', '0005_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='select',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='micro_server.bots', verbose_name='Боты'),
        ),
    ]
