# Generated by Django 4.0.2 on 2022-03-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_server', '0006_msg_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='content',
            field=models.TextField(default='Эта новость ещё не созрела =)', verbose_name='Содержание'),
        ),
    ]
